# Generated by Django 5.1.3 on 2024-11-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ticket_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
