# Generated by Django 5.1.3 on 2024-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_api", "0002_chatmessage_remove_message_conversation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
