# Generated by Django 5.1.3 on 2024-12-03 12:49

from django.db import migrations

def forward_func(apps, schema_editor):
    ChatSession = apps.get_model('chatbot_api', 'ChatSession')
    ChatMessage = apps.get_model('chatbot_api', 'ChatMessage')
    
    # Create a default session for existing messages
    default_session = ChatSession.objects.create()
    
    # Update all existing messages to use this session
    ChatMessage.objects.filter(chat_session__isnull=True).update(
        chat_session=default_session
    )

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_api", "0004_chatsession_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]

